<h1>PHPoton's frequently asked questions</h1>


<h2>Operational questions</h2>

<p><b>How can I join?</b><br>
Just follow [twitter:PHPoton] on Twitter and give the right answer to the questions.</p>

<p><b>How can I submit questions?</b><br>
You can add a question by using our <a href=/index/submit>submit form</a>.</p>

<p><b>Can I just use PHPoton with my group of friends?</b><br>
Not yet, but in the next version you can create your own groups (friends, companies etc).</p>


<h2>Behind the scenes</h2>

<p><b>Why have you created this bot?</b><br>
I thought it would be fun to create a tweet-bot that isn't annoying. But I guess it all depends on
your definition of annoying I guess.</p>

<p><b>Why the name PHPoton?</b><br>
At least I think it was a cool name.</p>

<p><b>What's with the "PHP" instead of "F"'s?</b><br>
It's the PHP way of doing things. The bot and the site is written in PHP and uses Zend Framework as
an application framework.</p>

<p><b>Will PHPoton be released as open source?</b><br>
Definitely, as soon as we are happy with the code, we will open it on GitHub :)</p>
