<h1>PHPoton's frequently asked questions</h1>

<p><b>How can I join?</b><br>
Just follow [twitter:PHPoton] on Twitter and give the right answer to the questions.</p>

<p><b>Why have you created this bot?</b><br>
I thought it would be fun to create a tweet-bot that isn't annoying.</p>

<p><b>Why the name PHPoton?</b><br>
At least I think it's a cool name.</p>

<p><b>What's with the "PHP" instead of "F"'s?</b><br>
It's the PHP way of doing things. The bot and the site is written in PHP and uses Zend Framework.</p>

<p><b>How can I submit questions?</b><br>
You can add a question by using our <a href=/index/submit>submit form</a>.</p>

<p><b>Can I just use PHPoton with my group of friends?</b><br>
Not yet, but in the next version you can create your own groups (friends, companies etc).</p>

<p><b>What will version 2 look like?</b><br>
Apart from the bugfixes and creating a decent layout, it will feature the following:

<ul>
<li>Only one answer per user is allowed
<li>More people will receive points (10, 7, 5, 3, 1 for instance)
<li>Questions will be alive for a longer period (so everybody get a change on answering the question)
<li>A better parser for the answer
</ul>
</p>

<p><b>Will PHPoton be released as open source?</b><br>
Definately, as soon as we are happy with the code :)</p>

