<h1>Welcome to phpoton</h1>

<p>PHPoton is a so-called tweetbot. PHPoton tweets a question and collects the answers that are tweeted back to him.
User who tweets the correct answer back to phpoton will receive points. The faster you tweet back the answer, the
more points you will collect.</p>

<h2>Want to join?</h2>
<p>It's easy! Just start following [twitter:PHPoton] and answer the questions phpoton will tweet.</p>

<h2>Submit a question?</h2>
<p>Do you have a question you like PHPoton to ask? <a href='/submit'>Submit it and get extra bonus points!</a></p>
