<h1>Welcome to phpoton</h1>

<p>PHPoton is an tweetbot. PHPoton tweets a question and collects the answers that are tweeted back. The user who tweets
the correct answer the quickest scores points.</p>


<h2>Who is currently inside the top-20?</h2>

<table>
<?php foreach ($this->topscore as $score) : ?>
  <tr>
    <td>Rank #<?php echo $this->escape($score->getRank());?></td>
    <td>[twitter:<?php echo $this->escape($score->getTwitterInfo()->getScreenName()); ?>]</td>
    <td><?php echo $this->escape($score->getPoints()); ?> Points</td>
  </tr>
<?php endforeach; ?>
</table>


<h2>Submit a question?</h2>
<p>Do you have a question you like PHPoton to ask? <a href='/submit'>Submit it!</a></p>
