<h1>Welcome to phpoton</h1>

<p>PHOoton is an tweetbot. PHPoton tweets a question and collects the answers that are tweeted back. The user who tweets
the correct answer the quickest scores points.</p>


<h2>Current highscore</h2>
<p>Who is currently inside the top-20?</p>


<table>
<?php foreach ($this->scoreboard as $score) : ?>
  <tr>
    <td>Rank #<?php echo $this->escape($score->rank);?></td>
    <td><?php echo $this->escape($score->username); ?></td>
    <td><?php echo $this->escape($score->points); ?> Points</td>
  </tr>
<?php endforeach; ?>
</table>


<h2>Submit a question?</h2>
<p>Do you have a question you like PHPoton to ask? <a href='/submit'>Submit it!</a></p>