<h2>Phpoton leader board</h2>

<?php echo $this->paginationControl($this->score, 'Sliding', 'paginator.phtml'); ?>
    
<table width=100%>
<?php foreach ($this->score as $score) : ?>
  <tr style="background-color: <?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next()?>">
    <td>Rank #<?php echo $this->escape($score->rank);?></td>
    <td>[twitter_id:<?php echo $this->escape($score->twitter_id); ?>]</td>
    <td><?php echo $this->escape($score->score_points); ?> Points</td>
  </tr>
<?php endforeach; ?>

  <tr><td colspan=3 style='background-color: #ccc'>&nbsp;</td></tr>
</table>

<?php echo $this->paginationControl($this->score, 'Sliding', 'paginator.phtml'); ?>
