<h2>Question statistics</h2>

<?php echo $this->paginationControl($this->stats, 'Sliding', 'paginator.phtml'); ?>

<table>
  <tr style="background-color: #D0D0D0">
    <th>Q #</th>
    <th>Replies</th>
    <th>Correct</th>
    <th>Ratio</th>
    <th>Question</th>
    <th>Answer</th>
    <th>Tweeted at</th>
    <th>Winner</th>
    <th>&nbsp;</th>
  </tr>
<?php foreach ($this->stats as $stat) : ?>
  <tr style="background-color: <?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next()?>">
    <td><?php echo $this->escape($stat->id); ?></td>
    <td><?php echo $this->escape($stat->replies); ?></td>
    <td><?php echo $this->escape($stat->correctReplies); ?></td>
    <td><?php
      if ($stat->replies == 0) {
          echo "";
      } else {
        printf("%.2f", ($stat->correctReplies / $stat->replies));
      } ?></td>
    <td><?php echo $this->escape($stat->question); ?></td>
    <td><?php echo $this->escape($stat->answer); ?></td>
    <td><?php echo $this->escape($stat->tweetedat); ?></td>
    <td><?php echo empty($stat->winner) ? "&nbsp;" : $this->escape($stat->winner); ?></td>
    <td><a href="<?php echo $this->url(array('action' => 'question', 'id' => $stat->id)); ?>">View details</a></td>
  </tr>
<?php endforeach; ?>
    <tr style="background-color: #D0D0D0"><td colspan=9>&nbsp;</td>
    </tr>
</table>
