<h3>Question statistics</h3>

<table>
  <tr><td>Question:</td><td><b><?php echo $this->escape($this->question->getQuestion()); ?></b></td></tr>
  <tr><td colspan=2>&nbsp;</td></tr>
  <tr><td>Tweeted on:</td><td><b><?php echo $this->escape($this->question->getTweetDt()); ?></b></td></tr>
  <tr><td>Replies:</td><td><b><?php echo $this->escape($this->question->getReplyCount()); ?></b></td></tr>
</table>