<h3>Question statistics</h3>

<?php echo $this->paginationControl($this->questions, 'Sliding', 'question-paginator.phtml'); ?>

<table>
  <tr><td>Question:</td><td><b><?php echo $this->escape($this->question->getQuestion()); ?></b></td></tr>
  <tr><td>Answer:</td><td><b><?php echo $this->escape($this->question->getAnswer()); ?></b></td></tr>
  <tr><td colspan=2>&nbsp;</td></tr>
  <tr><td>Tweeted on:</td><td><b><?php echo $this->escape($this->question->getTweetDt()); ?></b></td></tr>
  <tr><td>Status:</td><td><b><?php echo $this->escape($this->question->getStatus()); ?></b></td></tr>
  <tr><td>Replies:</td><td><b><?php echo $this->escape($this->question->getReplyCount()); ?></b></td></tr>
  <tr><td>Correct replies:</td><td><b><?php echo $this->escape($this->question->getReplyCount()); ?></b></td></tr>
  <tr><td>Winner:</td><td><b>[twitter:<?php if ($this->question->getWinnerTweep()) echo $this->escape($this->question->getWinnerTweep()->getScreenName()); ?>]</b></td></tr>
  <tr><td colspan=2>&nbsp;</td></tr>
</table>