<h3>Question statistics</h3>

<table>
  <tr><td>Question:</td><td><b><?php echo $this->escape($this->question->getQuestion()); ?></b></td></tr>
  <tr><td>Answer:</td><td><b><?php echo $this->escape($this->question->getAnswer()); ?></b></td></tr>
  <tr><td colspan=2>&nbsp;</td></tr>
  <tr><td>Tweeted on:</td><td><b><?php echo $this->escape($this->question->getTweetDt()); ?></b></td></tr>
  <tr><td>Status:</td><td><b><?php echo $this->escape($this->question->getStatus()); ?></b></td></tr>
  <tr><td>Replies:</td><td><b><?php echo $this->escape($this->question->getReplyCount()); ?></b></td></tr>
  <tr><td>Correct replies:</td><td><b><?php echo $this->escape($this->question->getReplyCount()); ?></b></td></tr>
  <tr><td>Winner:</td><td><b><?php echo ($this->question->getWinnerTweep()) ? $this->escape("[twitter:".$this->question->getWinnerTweep()->getScreenName()."]") : "timed out"; ?></b></td></tr>
  <tr><td colspan=2>&nbsp;</td></tr>
</table>