<h2>Admin</h2>

<?php echo $this->paginationControl($this->questions, 'Sliding', 'paginator.phtml'); ?>

<table>
    <tr style='background-color: gray; color: white'>
        <th>&nbsp;#&nbsp;</th>
        <th>Question</th>
        <th>Answer</th>
        <th>Status</th>
        <th>Command</th>
    </tr>
<?php
    foreach ($this->questions as $question) :
//    print "<pre>";
//    var_dump($question);
    switch ($question->getStatus()) {
        case "done" :
            $color = "#c0c0ff";
            break;
        case "moderation" :
            $color = "#ffff80";
            break;
        case "pending" :
            $color = "#80ff80";
            break;
        case "notapproved" :
            $color = "#ff8080";
            break;
        default :
            $color = "white";
            break;
    }
?>
    <tr style='background-color: <?php echo $color; ?>'>
        <td><?php echo $question->getId(); ?></td>
        <td><?php echo $question->getQuestion(); ?></td>
        <td><?php echo $question->getAnswer(); ?></td>
        <td><?php echo $question->getStatus(); ?></td>
<?php   if ($question->getStatus() == "notapproved") : ?>
        <td><form method=post><input type=hidden name=q value=<?php echo $question->getId();?>><input type=submit value='Accept'></form></td>
<?php   elseif ($question->getStatus() == "moderation" || $question->getStatus() == "pending") : ?>
        <td><form method=post><input type=hidden name=q value=<?php echo $question->getId();?>><input type=submit value='Dont accept'></form></td>
<?php   else : ?>
        <td>&nbsp;</td>
<?php   endif; ?>


    </tr>
<?php endforeach; ?>
</table>